from docx import Document
from docx.shared import Inches, Pt, RGBColor as DocxRGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH, WD_LINE_SPACING
from docx.enum.section import WD_ORIENT
from docx.oxml.ns import qn
from docx.oxml import OxmlElement
from pptx import Presentation
from pptx.util import Inches as PptInches
from pptx.util import Pt as PptPt
from pptx.dml.color import RGBColor as PptRGBColor
from pptx.enum.text import PP_ALIGN
from sqlalchemy.orm import Session
from . import models
from io import BytesIO
import re
from datetime import datetime


def export_project_to_file(db: Session, project_id: int, user_id: int) -> bytes:
    """
    Export a project to a document file based on its type (docx or pptx).
    
    Args:
        db: Database session
        project_id: ID of the project to export
        user_id: ID of the user requesting the export
        
    Returns:
        File content as bytes
        
    Raises:
        ValueError: If project not found or unauthorized
    """
    db_project = db.query(models.Project).filter(
        models.Project.id == project_id,
        models.Project.user_id == user_id
    ).first()
    
    if not db_project:
        raise ValueError("Project not found or unauthorized.")

    db_sections = db.query(models.Section).filter(
        models.Section.project_id == project_id
    ).order_by(models.Section.order_index).all()

    if db_project.doc_type.value == 'docx':
        return _generate_docx(db_project, db_sections)
    elif db_project.doc_type.value == 'pptx':
        return _generate_pptx(db_project, db_sections)
    else:
        raise ValueError("Unsupported document type.")

def _generate_docx(project, sections: list[models.Section]) -> bytes:
    """
    Generate a professionally formatted Word document from project data.
    
    Args:
        project: Project model containing document metadata
        sections: List of sections with their content
        
    Returns:
        Word document content as bytes
    """
    try:
        document = Document()

        # Set default document styling
        style = document.styles['Normal']
        font = style.font
        font.name = 'Calibri'
        font.size = Pt(11)

        # Set default paragraph formatting
        paragraph_format = style.paragraph_format
        paragraph_format.alignment = WD_ALIGN_PARAGRAPH.JUSTIFY
        paragraph_format.line_spacing_rule = WD_LINE_SPACING.ONE_POINT_FIVE
        paragraph_format.space_after = Pt(6)

        # Configure page layout
        section = document.sections[0]
        section.orientation = WD_ORIENT.PORTRAIT
        section.page_width = Inches(8.5)
        section.page_height = Inches(11)
        section.top_margin = Inches(1)
        section.bottom_margin = Inches(1)
        section.left_margin = Inches(1)
        section.right_margin = Inches(1)

        # Create title page
        title_para = document.add_paragraph()
        title_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
        title_run = title_para.add_run(project.title.upper())
        title_run.font.size = Pt(32)
        title_run.font.bold = True
        title_run.font.color.rgb = DocxRGBColor(0, 51, 102)  # Navy

        document.add_paragraph().add_run().add_break()  # spacer

        subtitle_para = document.add_paragraph()
        subtitle_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
        sub_run = subtitle_para.add_run(f"Main Topic: {project.main_prompt}")
        sub_run.font.size = Pt(16)
        sub_run.font.color.rgb = DocxRGBColor(70, 70, 70)

        document.add_paragraph().add_run().add_break()

        footer_para = document.add_paragraph()
        footer_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
        f_run = footer_para.add_run(
            f"Generated by OceanAI • {project.created_at.strftime('%B %d, %Y')}"
        )
        f_run.font.size = Pt(12)
        f_run.font.color.rgb = DocxRGBColor(100, 100, 100)

        document.add_page_break()


        # Add section content
        for section_item in sections:
            # Section header with border
            heading = document.add_heading(section_item.title, level=1)
            heading.alignment = WD_ALIGN_PARAGRAPH.LEFT
            heading.style = 'Heading 1'
            
            # Add subtle bottom border using XML
            p = document.add_paragraph()
            p.paragraph_format.space_before = Pt(0)
            p.paragraph_format.space_after = Pt(12)
            
            paragraph = p._p
            pBdr = OxmlElement('w:pBdr')
            bottom = OxmlElement('w:bottom')
            bottom.set(qn('w:val'), 'single')
            bottom.set(qn('w:sz'), '4')
            bottom.set(qn('w:space'), '1')
            bottom.set(qn('w:color'), 'D9D9D9')
            pBdr.append(bottom)
            paragraph.get_or_add_pPr().append(pBdr)

            # Extract and add content
            content_str = _extract_clean_content(section_item.content)
            if not content_str:
                p = document.add_paragraph("Analysis pending refinement.", style='Italic')
                p.runs[0].font.color.rgb = DocxRGBColor(120, 120, 120)
                continue

            lines = [line.strip() for line in content_str.split('\n') if line.strip()]
            is_bullet_list = any(line.startswith(('•', '-', '*')) for line in lines)

            if is_bullet_list:
                for line in lines:
                    clean_line = re.sub(r'^[\-\*\•]\s*', '', line).strip()
                    if not clean_line:
                        continue
                    p = document.add_paragraph(clean_line, style='List Bullet')
                    p.paragraph_format.alignment = WD_ALIGN_PARAGRAPH.JUSTIFY
                    p.paragraph_format.line_spacing_rule = WD_LINE_SPACING.ONE_POINT_FIVE
                    p.paragraph_format.space_after = Pt(6)
                    # Hanging indent
                    p.paragraph_format.left_indent = Inches(0.25)
                    p.paragraph_format.first_line_indent = Inches(-0.25)
            else:
                for para_text in lines:
                    if para_text:
                        p = document.add_paragraph(para_text)
                        p.paragraph_format.alignment = WD_ALIGN_PARAGRAPH.JUSTIFY
                        p.paragraph_format.line_spacing_rule = WD_LINE_SPACING.ONE_POINT_FIVE
                        p.paragraph_format.space_after = Pt(6)

        # Add footer with page numbers
        section = document.sections[0]
        footer = section.footer
        footer_para = footer.paragraphs[0] if footer.paragraphs else footer.add_paragraph()
        footer_para.text = "© OceanAI | Confidential"
        footer_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
        footer_para.runs[0].font.size = Pt(9)
        footer_para.runs[0].font.color.rgb = DocxRGBColor(100, 100, 100)

        # Add page number field
        pg_num = OxmlElement('w:pgNum')
        pg_num.set(qn('w:type'), 'decimal')
        footer_para._p.append(pg_num)

        # Save to memory
        file_stream = BytesIO()
        document.save(file_stream)
        file_stream.seek(0)
        return file_stream.read()
    except Exception as e:
        raise


def _generate_pptx(project, sections: list[models.Section]) -> bytes:
    """
    Generate a professionally formatted PowerPoint presentation from project data.
    
    Args:
        project: Project model containing presentation metadata
        sections: List of sections with their content
        
    Returns:
        PowerPoint presentation content as bytes
    """
    try:
        prs = Presentation()

        NAVY = PptRGBColor(0, 51, 102)
        BLACK = PptRGBColor(0, 0, 0)
        GRAY = PptRGBColor(80, 80, 80)

        # Create title slide
        slide = prs.slides.add_slide(prs.slide_layouts[0])
        title = slide.shapes.title
        subtitle = slide.placeholders[1]

        title.text = project.title
        title.text_frame.paragraphs[0].font.size = PptPt(40)
        title.text_frame.paragraphs[0].font.bold = True
        title.text_frame.paragraphs[0].font.color.rgb = NAVY

        subtitle.text = f"Main Topic: {project.main_prompt}\nGenerated by OceanAI"
        subtitle.text_frame.paragraphs[0].font.size = PptPt(20)
        subtitle.text_frame.paragraphs[0].font.color.rgb = GRAY

        # Create content slides
        for section_item in sections:
            if not section_item.content:
                continue

            slide = prs.slides.add_slide(prs.slide_layouts[1])
            title_shape = slide.shapes.title
            body_shape = slide.placeholders[1]

            title_shape.text = section_item.title
            title_shape.text_frame.paragraphs[0].font.size = PptPt(28)
            title_shape.text_frame.paragraphs[0].font.bold = True
            title_shape.text_frame.paragraphs[0].font.color.rgb = NAVY

            content_str = _extract_clean_content(section_item.content)
            if not content_str:
                body_shape.text = "Analysis pending refinement."
                body_shape.text_frame.paragraphs[0].font.italic = True
                body_shape.text_frame.paragraphs[0].font.color.rgb = GRAY
                continue

            lines = [re.sub(r'^[\-\*\•]\s*', '', line.strip()) for line in content_str.split('\n') if line.strip()]
            tf = body_shape.text_frame
            tf.clear()
            tf.word_wrap = True
            tf.margin_left = PptInches(0.2)
            tf.margin_right = PptInches(0.2)

            for i, line in enumerate(lines):
                if i >= 6:  # Max 6 bullet points
                    break
                p = tf.add_paragraph() if i > 0 else tf.paragraphs[0]
                p.text = line
                p.font.size = PptPt(24)
                p.font.color.rgb = BLACK
                p.level = 0
                p.space_after = PptPt(4)
                p.line_spacing = 1.2

            # Add footer
            footer_box = slide.shapes.add_textbox(PptInches(0.5), PptInches(6.8), PptInches(9), PptInches(0.3))
            footer_para = footer_box.text_frame.paragraphs[0]
            footer_para.text = "© OceanAI | Confidential"
            footer_para.font.size = PptPt(10)
            footer_para.font.color.rgb = GRAY
            footer_para.alignment = PP_ALIGN.CENTER

        # Save to memory
        file_stream = BytesIO()
        prs.save(file_stream)
        file_stream.seek(0)
        return file_stream.read()
    except Exception as e:
        raise


def _extract_clean_content(content_model) -> str:
    """
    Extract and clean content from structured content model.
    
    Args:
        content_model: Structured content model with body_json
        
    Returns:
        Cleaned content string
    """
    if not content_model:
        return ""

    # Extract body_json if it exists
    body = getattr(content_model, "body_json", None)
    
    # If body_json exists and is a list
    if isinstance(body, list) and body:
        parts = []
        for item in body:
            if isinstance(item, dict):
                # Handle {"type": "paragraph", "text": "content"}
                text = item.get("text") or item.get("content") or ""
                if text and isinstance(text, str):
                    parts.append(text)
            elif isinstance(item, str):
                parts.append(item)
        if parts:
            return "\n".join(parts)
    
    # Fallback: try to get string representation
    raw_text = str(content_model)
    
    # If it's the default "Content pending..." message, return empty
    if "Content pending" in raw_text or "failed to generate" in raw_text:
        return ""
    
    # Clean common AI artifacts
    raw_text = re.sub(r"(Content generation|This section|Based on the|Here are).*", "", raw_text, flags=re.IGNORECASE)
    raw_text = re.sub(r"---+", "", raw_text)
    raw_text = re.sub(r"```.*?```", "", raw_text, flags=re.DOTALL)
    raw_text = re.sub(r'\n\s*\n+', '\n\n', raw_text)
    return raw_text.strip()